server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: index-zuul-service8031
#  zipkin:
#    base-url: http://localhost:9411

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE8011
    api-b:
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE8051
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW8041
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  semaphore:
    max-semaphores: 200