server:
  port: 8090

eureka:
  client:
    #表示是否把自己注册到EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true此案呢过配合ribbon使用负载均衡
    fetchRegistry: true
    #注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: third-part-index-data-project8090
    #访问路径可以显示IP地址
    prefer-ip-address: true

spring:
  application:
    name: third-part-index-data-project8090
