server:
  port: 8011

spring:
  application:
    name: index-codes-service8011
#  zipkin:
#    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/