server:
  port: 8051
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service8051
#  zipkin:
#    base-url: http://localhost:9411

feign.hystrix.enabled: true
