#访问地址就是http://localhost:7001/
server:
  port: 8761

eureka:
  instance:
    hostname: localhost #表示主机名称
  client:
    #false表示不往注册中心注册自己
    register-with-eureka: false
    #fasle表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #http://localhost:8761
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #单机版
      #defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: eureka-server8761