server:
  port: 8021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: index-data-service8021
#  zipkin:
#    base-url: http://localhost:9411